MvcQR/Models/ErrorViewModel.cs
namespace MvcQR.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcQR/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcQR.Models;
using System.Diagnostics;

namespace MvcQR.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcQR/Controllers/QRController.cs
using Microsoft.AspNetCore.Mvc;
using MvcQR.Helpers;

namespace MvcQR.Controllers
{
    public class QRController : Controller
    {
        public HelperQR helper;

        public QRController(HelperQR helper)
        {
            this.helper = helper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string texto)
        {
            if (texto == null)
            {
                ViewData["mensaje"] = "Introduzca un texto";
                return View();
            }
            string qr = await this.helper.GenerarQR(texto);
            ViewData["qr"] = qr;

            return View();
        }
    }
}

MvcQR/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcQR/Views/QR/Index.cshtml
@{
    string qr = ViewData["qr"] as string;
}
<div class="container">
    <div class="text-center">
        <h2 class="text-black py-5">
            Generador de
            <span class="text-info">
                QR
            </span>
        </h2>
        <div class="py-3">
            <form method="post" class="row gap-2">
                <div class="col-md-8">
                    <input class="form-control" name="texto" id="texto" placeholder="Introduzca el texto..." />
                </div>
                <div class="col-md-3">
                    <button class="btn btn-outline-primary w-100">
                        generar QR
                    </button>
                </div>
            </form>
        </div>

        @if (qr != null)
        {
            <div>
                <img alt="qrgenerator" class="img-fluid" src="@string.Format("data:image/png;base64,{0}",qr)" height="300" width="300" />
            </div>
        }
        else
        {
            <p class="text-danger">
                @ViewData["mensaje"]
            </p>
        }
    </div>
</div>

MvcQR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcQR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcQR.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcQR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QR" asp-action="Index">Generador QR</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcQR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>